# model params
backbone_type: resnet_v2_m_50
loss_type: arcface
out_type: E

image_size: 112
embd_size: 512
class_num: 1140


# hyper params
bn_decay: 0.9
keep_prob: 0.4
weight_decay: !!float 5e-4
logits_scale: 64.0
logits_margin: 0.5
momentum: 0.9


# run params
val_bn_train: False
augment_flag: True
augment_margin: 16

gpu_num: 1
batch_size: 50
epoch_num: 5
step_per_epoch: 15000
val_freq: 2000

lr_steps: [40000, 60000, 80000]
lr_values: [0.004, 0.002, 0.0012, 0.0004]


# paths
pretrained_model: ""
# pretrained_model: '/data/hhd/InsightFace-tensorflow/output/20190120-133421/checkpoints/ckpt-m-140000'

train_data: ['data\VGGface2\vggface2_unbalanced.tfrecord']
# val_data: {'agedb_30': 'data\hhd\dataset\FaceData\InsightFace\faces_ms1s_arcface\agedb_30.bin', 'lfw': '\data\hhd\dataset\FaceData\InsightFace\faces_ms1m_arcface\lfw.bin', 'cfp_ff': '\data\hhd\dataset\FaceData\InsightFace\faces_ms1m_arcface\cfp_ff.bin', 'cfp_fp': '\data\hhd\dataset\FaceData\InsightFace\faces_ms1m_arcface\cfp_fp.bin', 'calfw': '\data\hhd\dataset\FaceData\InsightFace\faces_ms1m_arcface\calfw.bin', 'cplfw': '\data\hhd\dataset\FaceData\InsightFace\faces_ms1m_arcface\cplfw.bin', 'vgg2_fp': '\data\hhd\dataset\FaceData\InsightFace\faces_ms1m_arcface\vgg2_fp.bin'}
# val_data: {'agedb_30': 'data\eval\agedb_30.bin', 'VGGface2_1_test': 'data\eval\vggface2_1_test.bin'}
# val_data: {'lfw': 'data\eval\lfw.bin'}
# val_data: {'VGGface2_mixed_testing': 'data\eval\vggface2_mixed_testing.bin', 'VGGface2_1_test': 'data\eval\vggface2_1_test.bin', 'VGGface2_3_test': 'data\eval\vggface2_3_test.bin', 'VGGface2_mixed_val': 'data\eval\vggface2_mixed_val.bin', 'VGGface2_1_val': 'data\eval\vggface2_1_val.bin', 'VGGface2_3_val': 'data\eval\vggface2_3_val.bin'}
val_data: {'VGGface2_mixed_val': 'data\eval\vggface2_mixed_val.bin', 'VGGface2_1_val': 'data\eval\vggface2_1_val.bin', 'VGGface2_3_val': 'data\eval\vggface2_3_val.bin'}
# Kör bara ett dataset i val_data nästa gång vi testar!
output_dir: './output/vggface2/unbalanced'

